In [2]:
# Load pandas, other libraries
import pandas as pd
import numpy as np

In [4]:
# read PredictFlowStatsfile.csv
predict_flow_dataset = pd.read_csv('PredictFlowStatsfile.csv')
# Perform some exploration
predict_flow_dataset.head()

,timestamp,datapath_id,flow_duration_sec,flow_duration_nsec,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond
0,1.747109e+09,4,15945,420000000,0,0,0,0,0,0.0,0.0,0.0,0.0
1,1.747109e+09,4,9,662000000,0,0,0,0,0,0.0,0.0,0.0,0.0
2,1.747109e+09,5,15945,421000000,0,0,0,0,0,0.0,0.0,0.0,0.0
3,1.747109e+09,5,9,680000000,0,0,0,0,0,0.0,0.0,0.0,0.0
4,1.747109e+09,3,15945,423000000,0,0,0,0,0,0.0,0.0,0.0,0.0

In [5]:
predict_flow_dataset.describe()

,timestamp,datapath_id,flow_duration_sec,flow_duration_nsec,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond
count,1.116000e+03,1.116000e+03,1116.000000,1.116000e+03,1116.0,1116.0,1116.000000,1.116000e+03,1.116000e+03,1116.000000,1116.000000,1.116000e+03,1116.000000
mean,1.747109e+09,5.750880e+10,7109.179211,6.746550e+08,0.0,0.0,0.333333,4.654252e+05,1.954936e+07,1143.363831,0.004238,4.802574e+04,0.177980
std,2.686676e+02,1.286512e+11,7864.512870,1.665434e+08,0.0,0.0,1.106037,1.647484e+06,6.919470e+07,4442.307900,0.069372,1.865784e+05,2.913666
min,1.747109e+09,1.000000e+00,8.000000,0.000000e+00,0.0,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000
25%,1.747109e+09,2.000000e+00,403.500000,5.550000e+08,0.0,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000
50%,1.747109e+09,3.500000e+00,799.000000,6.860000e+08,0.0,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000
75%,1.747110e+09,5.000000e+00,16315.000000,7.900000e+08,0.0,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000
max,1.747110e+09,3.450528e+11,16865.000000,9.960000e+08,0.0,0.0,4.000000,6.451076e+06,2.709480e+08,33082.441026,2.150359,1.389477e+06,90.316016

In [6]:
predict_flow_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   timestamp                 1116 non-null   float64
 1   datapath_id               1116 non-null   int64
 2   flow_duration_sec         1116 non-null   int64
 3   flow_duration_nsec        1116 non-null   int64
 4   idle_timeout              1116 non-null   int64
 5   hard_timeout              1116 non-null   int64
 6   flags                     1116 non-null   int64
 7   packet_count              1116 non-null   int64
 8   byte_count                1116 non-null   int64
 9   packet_count_per_second   1116 non-null   float64
 10  packet_count_per_nsecond  1116 non-null   float64
 11  byte_count_per_second     1116 non-null   float64
 12  byte_count_per_nsecond    1116 non-null   float64
dtypes: float64(5), int64(8)
memory usage: 113.5 KB

In [8]:
predict_flow_dataset.columns

Index(['timestamp', 'datapath_id', 'flow_duration_sec', 'flow_duration_nsec',
       'idle_timeout', 'hard_timeout', 'flags', 'packet_count', 'byte_count',
       'packet_count_per_second', 'packet_count_per_nsecond',
       'byte_count_per_second', 'byte_count_per_nsecond'],
      dtype='object')

In [9]:
predict_flow_dataset.shape

(1116, 13)